// Generated by CoffeeScript 1.6.3
var MongoStore, app, domain, express, fs, https, login, loginCheck, options, path, profile, reimbursable, routes, timesheet;

express = require('express');

https = require('https');

fs = require('fs');

path = require('path');

MongoStore = require('connect-mongo')(express);

options = {
  pfx: fs.readFileSync('server.pfx'),
  requestCert: true
};

app = express();

domain = process.env.NODE_ENV === 'production' ? '192.168.23.1' : 'localhost';

app.configure(function() {
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.locals.pretty = true;
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express.cookieParser());
  app.use(express.session({
    secret: 'secret',
    store: new MongoStore({
      host: domain,
      db: 'session',
      clear_interval: 60 * 60
    }),
    cookie: {
      httpOnly: false,
      maxAge: new Date(Date.now() + 24 * 60 * 60 * 1000)
    }
  }));
  app.use(app.router);
  return app.use(express["static"](path.join(__dirname, 'public')));
});

app.configure('development', function() {
  app.set('port', process.env.PORT || 3000);
  return app.use(express.errorHandler());
});

app.configure('production', function() {
  app.set('port', process.env.PORT || 8080);
  return app.use(express.errorHandler());
});

loginCheck = function(req, res, next) {
  if (req.session.user) {
    return next();
  } else {
    return res.redirect('/login');
  }
};

routes = require('./routes');

app.get('/', loginCheck, routes.index);

login = require('./routes/login');

app.get('/login', login.get);

app.post('/login', login.post);

app.get('/login/logout', loginCheck, login.logout);

profile = require('./routes/profile');

app.get('/profile', loginCheck, profile.get);

timesheet = require('./routes/timesheet');

app.get('/timesheet', loginCheck, timesheet.get);

app.get('/timesheet/:yearMonth', loginCheck, timesheet.findThisMonth);

app.post('/timesheet', loginCheck, timesheet.post);

reimbursable = require('./routes/reimbursable');

app.get('/reimbursable', loginCheck, reimbursable.get);

https.createServer(options, app).listen(app.get('port'), function() {
  return console.log('Express server listening on port' + app.get('port'));
});
