// Generated by CoffeeScript 1.6.3
var TITLE, model;

model = require("../models/user.js");

TITLE = "Login";

exports.get = function(req, res) {
  if (req.session.user) {
    return res.redirect('/');
  } else {
    return res.render("login", {
      title: TITLE
    });
  }
};

exports.post = function(req, res) {
  var auth, crypto, email, md5, passHash, password, query, staff, userId;
  console.log(req.body);
  email = req.body.email;
  userId = '';
  query = {
    email: email
  };
  staff = model.staff;
  staff.findOne(query, function(err, data) {
    if (err) {
      console.log(err);
    }
    if (data && data.userId) {
      return userId = data.userId;
    }
  });
  password = req.body.password;
  crypto = require('crypto');
  md5 = function(str) {
    return crypto.createHash('md5').update(str + 'ponko23').digest("Hex");
  };
  passHash = md5(userId + password);
  console.log(passHash);
  query = {
    passHash: passHash
  };
  auth = model.auth;
  return auth.findOne(query, function(err, data) {
    if (err) {
      console.log(err);
    }
    console.log(data);
    if (data) {
      req.session.user = userId;
      console.log('true');
      return res.redirect("/");
    } else {
      console.log('false');
      return res.render("login", {
        title: TITLE
      });
    }
  });
};

exports.logout = function(req, res) {
  console.log(req.session);
  req.session.destroy();
  return res.redirect("/login");
};
