// Generated by CoffeeScript 1.6.3
var TITLE, model;

TITLE = "Login";

model = require("../models/user.js");

/*
  画面表示処理
  login済で開こうとするとホーム画面に移動する
*/


exports.get = function(req, res) {
  if (req.session.user) {
    return res.redirect('/');
  } else {
    return res.render("login", {
      title: TITLE
    });
  }
};

/*
  login処理
  mailaddressとpasswordからhasshを作成してデータベースにあるかを確認
  あればホーム画面を表示する
*/


exports.post = function(req, res) {
  var query, staff, userId;
  userId = '';
  query = {
    email: req.body.email
  };
  staff = model.staff;
  return staff.findOne(query, function(err, data) {
    var auth, crypto, md5;
    if (err) {
      console.log(err);
    }
    if (data && data.userId) {
      userId = data.userId;
    }
    crypto = require('crypto');
    md5 = function(str) {
      var keyword;
      keyword = 'ponko23';
      return crypto.createHash('md5').update(str + keyword).digest("Hex");
    };
    query = {
      passHash: md5(userId + req.body.password)
    };
    auth = model.auth;
    return auth.findOne(query, function(err, data) {
      if (err) {
        console.log(err);
      }
      if (data) {
        req.session.user = userId;
        return res.redirect("/");
      } else {
        return res.render("login", {
          title: TITLE
        });
      }
    });
  });
};

/*
  logout処理
  セッション破棄してログイン画面に戻る
*/


exports.logout = function(req, res) {
  req.session.destroy();
  return res.redirect("/login");
};
