// Generated by CoffeeScript 1.6.3
var TITLE, model, staff;

model = require("../models/user.js");

staff = model.staff;

TITLE = "Profile";

exports.get = function(req, res) {
  return res.render("profile", {
    title: TITLE,
    userName: '水口 康平'
  });
};
