// Generated by CoffeeScript 1.6.3
var Reimbursable, TITLE, model;

TITLE = "Reimbursable";

model = require("../models/reimbursable.js");

Reimbursable = model.reimbursable;

exports.get = function(req, res) {
  return res.render('reimbursable', {
    title: TITLE
  });
};
