// Generated by CoffeeScript 1.6.3
var TITLE, TimeSheet, model;

model = require("../models/timesheet.js");

TITLE = "TimeSheet";

TimeSheet = model.timesheet;

exports.get = function(req, res) {
  return res.render('timesheet', {
    title: TITLE
  });
};

exports.findThisMonth = function(req, res) {
  var query;
  query = {
    user: req.session.user,
    yearMonth: req.params.yearMonth.replace(/-/, "/")
  };
  return TimeSheet.find(query).sort('day').execFind(function(err, result) {
    if (err) {
      return res.send({
        'err': err
      });
    } else {
      return res.json(result);
    }
  });
};

exports.post = function(req, res) {
  var date, query;
  console.log(req.body);
  date = req.body.day.split('/');
  query = {
    user: req.session.user,
    yearMonth: date[0] + '/' + date[1],
    day: date[2]
  };
  return TimeSheet.findOne(query, function(err, result) {
    var addTimesheet, id, timesheet;
    if (result) {
      if (result.author) {
        res.redirect('/timesheet');
        return;
      }
      console.log(result);
      id = result._id;
      TimeSheet.remove({
        _id: id
      }, function(err) {});
    }
    if (req.body.delet === 'true') {
      console.log('delet!!');
    } else {
      timesheet = {
        "user": req.session.user,
        "yearMonth": date[0] + '/' + date[1],
        "day": date[2],
        "attendance": req.body.attendance
      };
      if (id) {
        timesheet["_id"] = id;
      }
      if (req.body.opening) {
        timesheet["opening"] = req.body.opening;
      }
      if (req.body.closing) {
        timesheet["closing"] = req.body.closing;
      }
      if (req.body.breakTime) {
        timesheet["breakTime"] = req.body.breakTime;
      }
      if (req.body.nightBreak) {
        timesheet["nightBreak"] = req.body.nightBreak;
      }
      if (req.body.note) {
        timesheet["note"] = req.body.note;
      }
      addTimesheet = new TimeSheet(timesheet);
      return addTimesheet.save(function(err) {
        if (err) {
          console.log(err);
          return res.redirect('back');
        } else {
          console.log('data save success!');
        }
      });
    }
  });
};
