// Generated by CoffeeScript 1.6.3
var TimeSheetSchema, db, domain, mongoose, url;

domain = (process.env.NODE_ENV === "production" ? "192.168.23.1" : "localhost");

mongoose = require("mongoose");

url = "mongodb://" + domain + "/timesheet";

db = mongoose.createConnection(url, function(err) {
  if (err) {
    return console.log("Error connected: " + url + " - " + err);
  } else {
    return console.log("Success connected: " + url);
  }
});

TimeSheetSchema = new mongoose.Schema({
  user: String,
  contract: String,
  yearMonth: String,
  day: Number,
  attendance: String,
  opening: String,
  closing: String,
  breakTime: String,
  nightBreak: String,
  note: String,
  author: String,
  date: Date
}, {
  collection: 'timesheets'
});

TimeSheetSchema.pre('save', function(next) {
  this.date = new Date();
  return next();
});

exports.timesheet = db.model("TimeSheet", TimeSheetSchema);
