// Generated by CoffeeScript 1.6.3
var authSchema, db, domain, mongoose, staffSchema, url;

domain = (process.env.NODE_ENV === "production" ? "192.168.23.1" : "localhost");

mongoose = require("mongoose");

url = "mongodb://" + domain + "/user";

db = mongoose.createConnection(url, function(err) {
  if (err) {
    return console.log("Error connected: " + url + " - " + err);
  } else {
    return console.log("Success connected: " + url);
  }
});

authSchema = new mongoose.Schema({
  passHash: String
}, {
  collection: 'authentication'
});

exports.auth = db.model("auth", authSchema);

staffSchema = new mongoose.Schema({
  userId: String,
  email: String,
  name: String,
  phonetic: String,
  birthDay: String,
  phone: String,
  zip: String,
  address: String,
  url: String,
  note: String
}, {
  collection: 'staff'
});

exports.staff = db.model("staff", staffSchema);
